NumPy Basics: I have covered all the topics in this notebook for NumPy

In [9]:
import numpy as np
list1 = [1,2,3,4,5]
arr1 = np.array(list1)

In [10]:
print(type(list1))
print(type(arr1))
print(list1)
print(arr1)

<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [11]:
np.__version__

'2.5.0'

In [12]:
tuple1 = (1,2,3,4,5)
range1 = range(1,6)
dict1 = {1: "A", 2: "B", 3: "C", 4: "D", 5: "E"}
set1 = {1,2,3,4,5}

print(type(tuple1))
print(type(range1))
print(type(dict1))
print(type(set1))

print(tuple1)
print(range1)
print(dict1)
print(set1)

<class 'tuple'>
<class 'range'>
<class 'dict'>
<class 'set'>
(1, 2, 3, 4, 5)
range(1, 6)
{1: 'A', 2: 'B', 3: 'C', 4: 'D', 5: 'E'}
{1, 2, 3, 4, 5}


In [13]:
arr_t = np.array(tuple1)
arr_r = np.array(range1)
arr_d = np.array(dict1)
arr_s = np.array(set1)

print(arr_t)
print(type(arr_t))

print(arr_r)
print(type(arr_r))

print(arr_d)
print(type(arr_d))

print(arr_s)
print(type(arr_s))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
{1: 'A', 2: 'B', 3: 'C', 4: 'D', 5: 'E'}
<class 'numpy.ndarray'>
{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


In [14]:
arr = np.array(42)
print(arr)

42


In [15]:
arr2d = np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])
print(arr2d)
print(type(arr2d))
print("Shape:", arr2d.shape)
print("Dimensions:", arr2d.ndim)

[[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]]
<class 'numpy.ndarray'>
Shape: (2, 2, 5)
Dimensions: 3


In [16]:
import numpy as np

arr3d = np.array([[[1, 2, 3], [4, 5, 6]],
                   [[7, 8, 9], [10, 11, 12]]])

print(arr3d)
print(type(arr3d))
print("Shape:", arr3d.shape)
print("Dimensions:", arr3d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
Shape: (2, 2, 3)
Dimensions: 3


In [17]:
array5d = np.array([[[[[1,2,3]]]]])
print(array5d)
print(type(array5d))
print(array5d.ndim)

[[[[[1 2 3]]]]]
<class 'numpy.ndarray'>
5


In [18]:
arr1

array([1, 2, 3, 4, 5])

In [19]:
arr1[0]

np.int64(1)

In [20]:
arr1[3]

np.int64(4)

In [21]:
arr1[2]+arr1[3]

np.int64(7)

In [22]:
array1d = np.array([1,2,3,4,5,6,7,8,9,10])
array2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
array3d = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[6,7,8,9,10],[1,2,3,4,5]]])
array4d = np.array([[[[1,2,3,4,5],[6,7,88,98,101]],[[61,71,81,91,102],[13,23,33,43,53]]],[[[11,22,33,44,55],[66,77,88,99,100]],[[65,75,8,9,10],[12,22,32,42,52]]]])

In [23]:
print(array1d[-1])
print(array2d[1,-1])
print(array3d[1,0,-1])
print(array4d[1,1,0,-1])

10
10
10
10


In [24]:
print(array1d[-3::2])
print(array2d[1,-3::2])
print(array3d[1,0,-3::2])
print(array4d[1,1,0,-3::2])

[ 8 10]
[ 8 10]
[ 8 10]
[ 8 10]


In [25]:
print(array1d[::2])
print(array2d[1,::2])
print(array3d[1,0,::2])
print(array4d[1,1,0,::2])

[1 3 5 7 9]
[ 6  8 10]
[ 6  8 10]
[65  8 10]


In [26]:

print(array4d[:,:,:,-3:])

[[[[  3   4   5]
   [ 88  98 101]]

  [[ 81  91 102]
   [ 33  43  53]]]


 [[[ 33  44  55]
   [ 88  99 100]]

  [[  8   9  10]
   [ 32  42  52]]]]


In [27]:
print(array4d.dtype)

int64


In [28]:
arraystr = np.array(["Ayushi","Gupta"], dtype = "S")

In [29]:
print(arraystr.dtype)
print(arraystr)

|S6
[b'Ayushi' b'Gupta']


In [30]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [31]:
import numpy as np

arr = np.array([1.1, 2.6, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [32]:
array1 = np.array([1.1, 2.6, 3.1])
array2 = array1.view()


In [33]:
array2.reshape(3,1)

array([[1.1],
       [2.6],
       [3.1]])

In [34]:
print(array1)
print(array2)
array2.astype(int)

[1.1 2.6 3.1]
[1.1 2.6 3.1]


array([1, 2, 3])

In [35]:
array1

array([1.1, 2.6, 3.1])

In [36]:
array2[1]=6

In [37]:
array1

array([1.1, 6. , 3.1])

In [38]:
array4d.shape

(2, 2, 2, 5)

In [39]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [40]:
array4d.reshape(-1)

array([  1,   2,   3,   4,   5,   6,   7,  88,  98, 101,  61,  71,  81,
        91, 102,  13,  23,  33,  43,  53,  11,  22,  33,  44,  55,  66,
        77,  88,  99, 100,  65,  75,   8,   9,  10,  12,  22,  32,  42,
        52])

In [41]:
array4d

array([[[[  1,   2,   3,   4,   5],
         [  6,   7,  88,  98, 101]],

        [[ 61,  71,  81,  91, 102],
         [ 13,  23,  33,  43,  53]]],


       [[[ 11,  22,  33,  44,  55],
         [ 66,  77,  88,  99, 100]],

        [[ 65,  75,   8,   9,  10],
         [ 12,  22,  32,  42,  52]]]])

In [42]:
print(array4d.base)

None


In [43]:
for x in array4d:
    print(x)

[[[  1   2   3   4   5]
  [  6   7  88  98 101]]

 [[ 61  71  81  91 102]
  [ 13  23  33  43  53]]]
[[[ 11  22  33  44  55]
  [ 66  77  88  99 100]]

 [[ 65  75   8   9  10]
  [ 12  22  32  42  52]]]


In [44]:
for x in array4d:
    for y in x:
        for z in y:
            for a in z:
                print(a)

1
2
3
4
5
6
7
88
98
101
61
71
81
91
102
13
23
33
43
53
11
22
33
44
55
66
77
88
99
100
65
75
8
9
10
12
22
32
42
52


In [45]:
for x in np.nditer(array4d):
  print(x)x

SyntaxError: invalid syntax (4233239606.py, line 2)

In [ ]:
for x in np.nditer(array4d, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'88')
np.bytes_(b'98')
np.bytes_(b'101')
np.bytes_(b'61')
np.bytes_(b'71')
np.bytes_(b'81')
np.bytes_(b'91')
np.bytes_(b'102')
np.bytes_(b'13')
np.bytes_(b'23')
np.bytes_(b'33')
np.bytes_(b'43')
np.bytes_(b'53')
np.bytes_(b'11')
np.bytes_(b'22')
np.bytes_(b'33')
np.bytes_(b'44')
np.bytes_(b'55')
np.bytes_(b'66')
np.bytes_(b'77')
np.bytes_(b'88')
np.bytes_(b'99')
np.bytes_(b'100')
np.bytes_(b'65')
np.bytes_(b'75')
np.bytes_(b'8')
np.bytes_(b'9')
np.bytes_(b'10')
np.bytes_(b'12')
np.bytes_(b'22')
np.bytes_(b'32')
np.bytes_(b'42')
np.bytes_(b'52')


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [ ]:
from numpy import random
x = random.randint(100, size = (3,2,5))
print(x)

[[[46 19 20 78  8]
  [70 26 62 16  0]]

 [[63 88 71 25 31]
  [45 16 34 66 80]]

 [[14 59 63 84 59]
  [89 93 67 14 71]]]


In [47]:
x = [1,2,3,4]
y = [4,5,6,7]
z = []

for i, j in zip(x,y):
    z.append(i+j)
print(z)

[5, 7, 9, 11]


In [48]:
z = np.add(x,y)

In [49]:
z

array([ 5,  7,  9, 11])

In [50]:
z^2

array([ 7,  5, 11,  9])

In [51]:
z*2

array([10, 14, 18, 22])

In [53]:
z**[2,1,2,1]

array([25,  7, 81, 11])

In [54]:
z*[2,1,2,1]

array([10,  7, 18, 11])

In [55]:
z+[2,1,2,1]

array([ 7,  8, 11, 12])

In [56]:
np.add(z,[2,1,2,1])

array([ 7,  8, 11, 12])