# NumPy Complete Guide

## What is NumPy?

NumPy (Numerical Python) is the fundamental library for numerical computing in Python. It provides fast multidimensional arrays and a rich collection of mathematical, statistical, linear algebra, and random number generation functions.

### Why NumPy?
- Faster than Python lists
- Memory efficient
- Supports vectorized operations
- Foundation for Pandas, Scikit-learn, TensorFlow, and PyTorch

In this notebook, you'll learn the major NumPy functions with examples and practice exercises.


In [1]:
import numpy as np
print('NumPy Version:', np.__version__)

NumPy Version: 2.5.0


## Creating Arrays

In [2]:
a=np.array([1,2,3,4])
b=np.arange(1,11)
c=np.linspace(0,100,11)
d=np.zeros((2,3))
e=np.ones((2,3))
f=np.eye(3)
print(a,b,c,d,e,f,sep='\n\n')

[1 2 3 4]

[ 1  2  3  4  5  6  7  8  9 10]

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Array Attributes

In [3]:
arr=np.arange(12).reshape(3,4)
print(arr)
print("Shape:",arr.shape)
print("Dimensions:",arr.ndim)
print("Size:",arr.size)
print("Datatype:",arr.dtype)
print("Item Size:",arr.itemsize)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)
Dimensions: 2
Size: 12
Datatype: int64
Item Size: 8


## Indexing and Slicing

In [4]:
print(arr[1,2])
print(arr[:,1])
print(arr[1:])
print(arr[::-1])

6
[1 5 9]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


## Reshaping

In [5]:
x=np.arange(12)
print(x.reshape(3,4))
print(x.flatten())
print(x.reshape(3,4).T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Mathematical Functions

In [6]:
print(np.sqrt(np.arange(1,10)))
print(np.power(np.arange(1,6),2))
print(np.exp([1,2,3]))
print(np.log([1,2,3]))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[ 1  4  9 16 25]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]


## Statistical Functions

In [7]:
marks=np.array([75,82,90,68,99,55,88,72])
print(np.mean(marks))
print(np.median(marks))
print(np.std(marks))
print(np.min(marks))
print(np.max(marks))
print(np.sum(marks))

78.625
78.5
13.095204274848102
55
99
629


## Sorting and Searching

In [8]:
arr=np.array([5,8,1,7,3])
print(np.sort(arr))
print(np.argsort(arr))
print(np.where(arr>4))
print(np.unique([1,2,2,3,4,4]))

[1 3 5 7 8]
[2 4 0 3 1]
(array([0, 1, 3]),)
[1 2 3 4]


## Boolean Masking

In [9]:
arr=np.arange(1,21)
print(arr[arr%2==0])
print(arr[arr>10])

[ 2  4  6  8 10 12 14 16 18 20]
[11 12 13 14 15 16 17 18 19 20]


## Broadcasting

In [10]:
a=np.array([1,2,3])
print(a+10)
print(a*5)

[11 12 13]
[ 5 10 15]


## Random Module

In [11]:
np.random.seed(42)
print(np.random.rand(5))
print(np.random.randint(1,100,10))

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
[83 87 75 75 88 24  3 22 53  2]


## Linear Algebra

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(np.dot(A,B))
print(np.linalg.det(A))
print(np.linalg.inv(A))

## Useful Functions

In [ ]:
a=np.array([1,2,3])
print(np.append(a,4))
print(np.insert(a,1,100))
print(np.delete(a,1))
print(np.repeat(a,2))
print(np.tile(a,3))
print(np.flip(a))

# Practice Exercise 1

Create a NumPy array containing numbers from **1 to 50**.

Tasks:
1. Find shape.
2. Convert into a 5×10 matrix.
3. Display even numbers.
4. Find mean, median and standard deviation.
5. Replace values greater than 40 with 100.
6. Sort in descending order.
7. Find indices divisible by 5.


# Practice Exercise 2

## Student Marks Analysis

marks=[78,45,88,67,91,56,73,84,39,61,95,82,70,64,58]

Tasks:
1. Convert into NumPy array.
2. Calculate average.
3. Find highest and lowest marks.
4. Count students above 75.
5. Display failed students (<40).
6. Add 5 grace marks.
7. Cap marks at 100.
8. Sort marks.
9. Display top 3 marks.


# Summary

You learned:

- Array creation
- Array attributes
- Indexing & slicing
- Reshaping
- Mathematical operations
- Statistical functions
- Sorting & searching
- Boolean masking
- Broadcasting
- Random module
- Linear algebra
- Utility functions

Happy Learning!
